"""debug

Revision ID: 02aa0591de4c
Revises: 39e5d731fb6e
Create Date: 2025-05-22 07:27:01.216821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02aa0591de4c'
down_revision = '39e5d731fb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False, server_default="Unknown"))
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=False, server_default="Unknown"))
        batch_op.add_column(sa.Column('team_size', sa.Integer(), nullable=False, server_default="1"))
        batch_op.add_column(sa.Column('statement_path', sa.String(length=255), nullable=False, server_default="Unknown"))
        batch_op.add_column(sa.Column('school_permission_path', sa.String(length=255), nullable=False, server_default="Unknown"))
        batch_op.add_column(sa.Column('nisn_path', sa.String(length=255), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('student_card_path', sa.String(length=255), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('selfie_path', sa.String(length=255), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('birth_certificate_path', sa.String(length=255), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('report_card_path', sa.String(length=255), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('non_athlete_statement_path', sa.String(length=255), nullable=False, server_default="0"))
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.drop_column('username')
        batch_op.drop_column('competition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competition', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.drop_column('non_athlete_statement_path')
        batch_op.drop_column('report_card_path')
        batch_op.drop_column('birth_certificate_path')
        batch_op.drop_column('photo_path')
        batch_op.drop_column('selfie_path')
        batch_op.drop_column('student_card_path')
        batch_op.drop_column('nisn_path')
        batch_op.drop_column('school_permission_path')
        batch_op.drop_column('statement_path')
        batch_op.drop_column('team_size')
        batch_op.drop_column('school')
        batch_op.drop_column('full_name')

    op.create_table('registrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('school', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('member_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('competition', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('statement_letter_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('school_permission_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('nisn_document_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('student_card_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('selfie_photo_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('passport_photo_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('birth_certificate_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('academic_transcript_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('non_athlete_statement_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='registrations_pkey')
    )
    # ### end Alembic commands ###
